### ISSUE TITLE
Learn how to spell recipe

### ISSUE THREAD

**Issue by gxnda** [DanielDobromylskyj/McFc-v3#1]
recipe
recipe
recipe
recipe
recipe
recipe
recipe
recipe
recipe
recipe
recipe
recipe

**Comment by DanielDobromylskyj** [comment]
This is correct. Yet mojang also can't spell in their datapacks (when this was made). So, for consistency, that's what it's called.

**Comment by gxnda** [comment]
> This is correct. Yet mojang also can't spell in their datapacks (when this was made). So, for consistency, that's what it's called.

ew sorry
